[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  [context.production.environment]
    VITE_AIRTABLE_API_KEY = ""
    VITE_AIRTABLE_BASE_ID = ""
    VITE_AIRTABLE_TABLE_NAME = ""
    VITE_API_URL = ""
    VITE_APP_ENV = "production"
  
  [context.deploy-preview.environment]
    VITE_AIRTABLE_API_KEY = ""
    VITE_AIRTABLE_BASE_ID = ""
    VITE_AIRTABLE_TABLE_NAME = ""
    VITE_API_URL = ""
    VITE_APP_ENV = "staging"
  
  [context.branch-deploy.environment]
    VITE_AIRTABLE_API_KEY = ""
    VITE_AIRTABLE_BASE_ID = ""
    VITE_AIRTABLE_TABLE_NAME = ""
    VITE_API_URL = ""
    VITE_APP_ENV = "development"